contents:
  - name: c-cpp-properties
    codes:
      - c-cpp-properties.json
  - name: cpp
    codes:
      - cpp.json
  - name: fast-io
    codes:
      - fast-io.hpp
  - name: io-sync-off
    codes:
      - io-sync-off.hpp
  - name: launch
    codes:
      - launch.json
  - name: optimize-header
    codes:
      - optimize-header.h
  - name: settings
    codes:
      - settings.json
  - name: tasks
    codes:
      - tasks.json
