contents:
  - name: 环境配置
    directory: config
  - name: 算法
    directory: algorithm
  - name: 数据结构
    directory: data_structure
  - name: 图论
    directory: graph
  - name: 数学
    directory: math
  - name: 字符串
    directory: string
