contents:
  - name: 组合数
    codes:
      - comb.hpp
  - name: 计算几何（旧）
    codes:
      - computation-geometry.hpp
  - name: 计算几何（新）
    codes:
      - flat-geometry.hpp
  - name: 卷积
    codes:
      - conv.hpp
  - name: 按值域预处理的快速 gcd
    codes:
      - gcd.hpp
  - name: 拉格朗日插值
    codes:
      - lagrange.hpp
  - name: 线性代数
    codes:
      - linear.hpp
  - name: modint
    codes:
      - mod-int.hpp
  - name: 光速幂
    codes:
      - speed-of-light-power.hpp
  - name: 数论分块
    codes:
      - sqrt-decomposition.hpp
  - name: 数学工具
    codes:
      - utils.hpp
  - name: 数列逆元
    codes:
      - vec-inv.hpp
