contents:
  - name: graph
    codes:
      - graph.hpp
  - name: grid
    codes:
      - grid.hpp
  - name: hld
    codes:
      - hld.hpp
  - name: lca
    codes:
      - lca.hpp
  - name: twosat
    codes:
      - twosat.hpp
  - name: maxflow
    codes:
      - maxflow.hpp
